Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,6 +11,17 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       
+      - name: Install PM2
+        run: npm install pm2 -g
+
+      - name: Start PM2
+        run: |
+          pm2 start index.js
+          if [ $? -ne 0 ]; then
+            echo "Failed to start PM2. Exiting..."
+            exit 1
+          fi
+          
       - name: multiple command
         uses: appleboy/ssh-action@v1.0.3
         with:
@@ -21,5 +32,4 @@ jobs:
           script: |
                 whoami
                 ls -al
-                npm install pm2 -g
-                pm2 start index.js
+                
