Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,16 +11,16 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       
-      - name: Install PM2
-        run: npm install pm2 -g
+      # - name: Install PM2
+      #   run: npm install pm2 -g
 
-      - name: Start PM2
-        run: |
-          pm2 start index.js
-          if [ $? -ne 0 ]; then
-            echo "Failed to start PM2. Exiting..."
-            exit 1
-          fi
+      # - name: Start PM2
+      #   run: |
+      #     pm2 start index.js
+      #     if [ $? -ne 0 ]; then
+      #       echo "Failed to start PM2. Exiting..."
+      #       exit 1
+      #     fi
           
       - name: multiple command
         uses: appleboy/ssh-action@v1.0.3
